version: '3.8'

services:
  # Kind кластер
  kind-control-plane:
    image: kindest/node:v1.27.3
    container_name: kind-control-plane
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k8s:/k8s
      - ./kind-config:/kind-config
    command: >
      /bin/sh -c "
      kind create cluster --name local --config=/kind-config/kind-config.yaml --wait 5m &&
      kubectl apply -f /k8s/app.yml &&
      kubectl apply -f /k8s/prometheus.yml &&
      kubectl apply -f /k8s/grafana.yml &&
      tail -f /dev/null
      "
    networks:
      - kind-net

  # Утилита для управления кластером
  kubectl:
    image: bitnami/kubectl:latest
    depends_on:
      - kind-control-plane
    volumes:
      - ./k8s:/k8s
      - ~/.kube:/root/.kube
    entrypoint: >
      /bin/sh -c "
      kubectl cluster-info &&
      kubectl get nodes &&
      kubectl get pods -A &&
      tail -f /dev/null
      "
    networks:
      - kind-net

networks:
  kind-net:
    driver: bridge