version: '3.8'

services:
  k8s-manager:
    build: .
    container_name: k8s-manager
    privileged: true
    network_mode: host  # Лучше для Minikube на Ubuntu 24.04
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k8s-config:/k8s-config  # Для горячего редактирования конфигов
    environment:
      - MINIKUBE_HOME=/minikube
    ports:
      - "30080:30080"  # NodePort для приложения
      - "30900:30900"  # Grafana