grafana:
  service:
    type: NodePort
    nodePort: 30900
  adminPassword: "admin"  # Пароль для Grafana
prometheus:
  service:
    type: NodePort
alertmanager:
  enabled: false  # Отключаем Alertmanager (если не нужен)